site_url: ""
site_name: My Docs

nav:
  - Home: index.md

  - Maya:
      - Overview: maya/index.md
      - Export: maya/test.md

  - Blender:
      - Overview: Blender/index.md
      - Export: Blender/Blender.md

  - ZBrush:
      - Overview: ZBrush/index.md
      - Export: ZBrush/Decimation_Master.md
      - Test: ZBrush/test.md

  - Nomad:
      - Overview: nomad.md

theme:
  name: material




theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
